blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooCodeInc/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for Datacoves Copilot
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.roo-cline&ssr=false#review-details
      about: Enjoying Datacoves Copilot? Leave a review here!
